"""Go file discovery, exclusions and file-level robustness in FrameScanner."""

from pathlib import Path

from frame.sil import FrameScanner
from frame.sil.scanner import skip_go_file

VULN = '''package main
import ("net/http"; "os/exec")
func h(w http.ResponseWriter, r *http.Request) { exec.Command(r.FormValue("c")).Run() }
'''


def test_skip_rules(tmp_path: Path):
    files = {
        "main.go": VULN,
        "vendor/x/a.go": VULN,
        "pkg/testdata/b.go": VULN,
        "third_party/c.go": VULN,
        "main_test.go": VULN,
        "api.pb.go": VULN,
        "zz_generated.deepcopy.go": VULN,
        "store_mock.go": VULN,
        "gen.go": "// Code generated by stringer; DO NOT EDIT.\n\n" + VULN,
    }
    for rel, body in files.items():
        p = tmp_path / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(body)
    kept = {rel for rel in files if not skip_go_file(tmp_path / rel, tmp_path)}
    assert kept == {"main.go"}


def test_directory_scan_uses_exclusions(tmp_path: Path):
    (tmp_path / "main.go").write_text(VULN)
    (tmp_path / "vendor").mkdir()
    (tmp_path / "vendor" / "v.go").write_text(VULN)
    results = FrameScanner(language="go", verify=False).scan_directory(str(tmp_path), "**/*.go")
    assert [Path(r.filename).name for r in results] == ["main.go"]
    assert "CWE-78" in {v.cwe_id for v in results[0].vulnerabilities}


def test_scan_file_detects_go_from_extension(tmp_path: Path):
    p = tmp_path / "main.go"
    p.write_text(VULN)
    result = FrameScanner(verify=False).scan_file(str(p))        # default language: python
    assert "CWE-78" in {v.cwe_id for v in result.vulnerabilities}


def test_scan_file_tolerates_crlf_bom_and_bad_bytes(tmp_path: Path):
    p = tmp_path / "main.go"
    p.write_bytes(b"\xef\xbb\xbf" + VULN.replace("\n", "\r\n").encode() + b"// \xff\xfe\r\n")
    result = FrameScanner(language="go", verify=False).scan_file(str(p))
    assert "CWE-78" in {v.cwe_id for v in result.vulnerabilities}


def test_explicit_scan_of_generated_file_still_analyses_it():
    src = "// Code generated by x; DO NOT EDIT.\n\n" + VULN
    result = FrameScanner(language="go", verify=False).scan(src, "gen.go")
    assert "CWE-78" in {v.cwe_id for v in result.vulnerabilities}


def test_generated_header_in_string_literal_is_not_skipped(tmp_path: Path):
    # The marker text sits inside a raw string literal (real generator source,
    # not a generator's output), well after `package main`. A whole-file
    # search would false-positive on it; only the leading comment block, up
    # to the first non-comment/non-blank line, counts.
    src = (VULN + "\nconst tmpl = `\n"
           "// Code generated by x. DO NOT EDIT.\n"
           "`\n")
    p = tmp_path / "gen_template.go"
    p.write_text(src)
    assert not skip_go_file(p, tmp_path)


def test_block_comment_header_is_skipped(tmp_path: Path):
    # The common Kubernetes generated-file shape: a `/* ... */` license block
    # comment, then the `//` marker, then `package`. The block comment must be
    # skipped over (its lines are still "before the first non-comment,
    # non-blank text"), not treated as the end of the leading comment run.
    src = ("/*\nCopyright The Kubernetes Authors.\n*/\n\n"
           "// Code generated by client-gen. DO NOT EDIT.\n\n"
           + VULN)
    p = tmp_path / "pod.go"
    p.write_text(src)
    assert skip_go_file(p, tmp_path)


def test_real_generated_header_is_skipped(tmp_path: Path):
    src = "// Code generated by protoc-gen-go. DO NOT EDIT.\n\n" + VULN
    p = tmp_path / "api.go"
    p.write_text(src)
    assert skip_go_file(p, tmp_path)


def test_generated_header_with_bom_is_skipped(tmp_path: Path):
    src = "// Code generated by protoc-gen-go. DO NOT EDIT.\n\n" + VULN
    p = tmp_path / "api_bom.go"
    p.write_bytes(b"\xef\xbb\xbf" + src.encode())
    assert skip_go_file(p, tmp_path)


def test_generated_header_after_package_clause_is_not_skipped(tmp_path: Path):
    # The marker only means something in the file's leading comment block
    # (before `package`), per Go convention. The same text appearing later
    # (e.g. a stray comment describing something else) does not mark the
    # file as generated.
    src = ("package main\n\n"
           "// Code generated by x. DO NOT EDIT.\n\n"
           + VULN.split("\n", 1)[1])
    p = tmp_path / "not_generated.go"
    p.write_text(src)
    assert not skip_go_file(p, tmp_path)


def test_scan_root_named_vendor_still_scans_its_files(tmp_path: Path):
    # The exclusion is about a `vendor` (etc.) directory *inside* the scanned
    # tree, not about the scan root's own name -- a project whose root
    # happens to sit under a path segment named `vendor` must still be
    # scanned normally.
    root = tmp_path / "vendor"
    root.mkdir()
    (root / "main.go").write_text(VULN)
    results = FrameScanner(language="go", verify=False).scan_directory(str(root), "**/*.go")
    assert [Path(r.filename).name for r in results] == ["main.go"]
    assert "CWE-78" in {v.cwe_id for v in results[0].vulnerabilities}
