"""Go file discovery, exclusions and file-level robustness in FrameScanner."""

from pathlib import Path

from frame.sil import FrameScanner
from frame.sil.scanner import skip_go_file

VULN = '''package main
import ("net/http"; "os/exec")
func h(w http.ResponseWriter, r *http.Request) { exec.Command(r.FormValue("c")).Run() }
'''


def test_skip_rules(tmp_path: Path):
    files = {
        "main.go": VULN,
        "vendor/x/a.go": VULN,
        "pkg/testdata/b.go": VULN,
        "third_party/c.go": VULN,
        "main_test.go": VULN,
        "api.pb.go": VULN,
        "zz_generated.deepcopy.go": VULN,
        "store_mock.go": VULN,
        "gen.go": "// Code generated by stringer; DO NOT EDIT.\n\n" + VULN,
    }
    for rel, body in files.items():
        p = tmp_path / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(body)
    kept = {rel for rel in files if not skip_go_file(tmp_path / rel, tmp_path)}
    assert kept == {"main.go"}


def test_directory_scan_uses_exclusions(tmp_path: Path):
    (tmp_path / "main.go").write_text(VULN)
    (tmp_path / "vendor").mkdir()
    (tmp_path / "vendor" / "v.go").write_text(VULN)
    results = FrameScanner(language="go", verify=False).scan_directory(str(tmp_path), "**/*.go")
    assert [Path(r.filename).name for r in results] == ["main.go"]
    assert "CWE-78" in {v.cwe_id for v in results[0].vulnerabilities}


def test_scan_file_detects_go_from_extension(tmp_path: Path):
    p = tmp_path / "main.go"
    p.write_text(VULN)
    result = FrameScanner(verify=False).scan_file(str(p))        # default language: python
    assert "CWE-78" in {v.cwe_id for v in result.vulnerabilities}


def test_scan_file_tolerates_crlf_bom_and_bad_bytes(tmp_path: Path):
    p = tmp_path / "main.go"
    p.write_bytes(b"\xef\xbb\xbf" + VULN.replace("\n", "\r\n").encode() + b"// \xff\xfe\r\n")
    result = FrameScanner(language="go", verify=False).scan_file(str(p))
    assert "CWE-78" in {v.cwe_id for v in result.vulnerabilities}


def test_explicit_scan_of_generated_file_still_analyses_it():
    src = "// Code generated by x; DO NOT EDIT.\n\n" + VULN
    result = FrameScanner(language="go", verify=False).scan(src, "gen.go")
    assert "CWE-78" in {v.cwe_id for v in result.vulnerabilities}
